/*
 * generated by Xtext 2.38.0
 */
package org.xtext.componentsystem.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDslScopeProvider extends DelegatingScopeProvider {
}
