<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="MDSDComponentMetamodel" nsURI="http://www.example.org/MDSDComponentMetamodel"
    nsPrefix="MDSDComponentMetamodel">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Repository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//BasicComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" upperBound="-1"
        eType="#//Interface" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedInterfaces" upperBound="-1"
        eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedServices" upperBound="-1"
        eType="#//Service" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredInterfaces" upperBound="-1"
        eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviorDescription" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signatures" upperBound="-1"
        eType="#//Signature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Signature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Service">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingSignature"
        lowerBound="1" eType="#//Signature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="InternalAction" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalCall" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Branch" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssemblyContext">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="providedInterfacesMatch requiredInterfacesMatch"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="providedInterfacesMatch" value="self.providedRoles->forAll(r | self.component.providedInterfaces->includes(r.interface))"/>
      <details key="requiredInterfacesMatch" value="self.requiredRoles->forAll(r | self.component.requiredInterfaces->includes(r.interface))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedRoles" upperBound="-1"
        eType="#//Role" containment="true" eOpposite="#//Role/providedAssemblyContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredRoles" upperBound="-1"
        eType="#//Role" containment="true" eOpposite="#//Role/requiredAssemblyContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocationContext" eType="#//AllocationContext"
        eOpposite="#//AllocationContext/assemblyContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assembly">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assemblyContexts" upperBound="-1"
        eType="#//AssemblyContext" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compositeComponents" upperBound="-1"
        eType="#//CompositeComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="delegationConnectors" upperBound="-1"
        eType="#//DelegationConnector" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assemblyConnectors" upperBound="-1"
        eType="#//AssemblyConnector" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="noAllocatedAssemblyContextsInCompositeComponents"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="noAllocatedAssemblyContextsInCompositeComponents" value="&#xA;&#x9;&#x9;self.allocation.allocationContexts->forAll(ac | &#xA;&#x9;&#x9;&#x9;self.assembly.compositeComponents->forAll(cc | &#xA;&#x9;&#x9;&#x9;&#x9;cc.assemblyContexts->excludes(ac.assemblyContext)&#xA;&#x9;&#x9;&#x9;)&#xA;&#x9;&#x9;)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" lowerBound="1"
        upperBound="-1" eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assembly" lowerBound="1"
        eType="#//Assembly" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocation" lowerBound="1"
        eType="#//Allocation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environment" lowerBound="1"
        eType="#//Environment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeComponent" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assemblyContexts" lowerBound="2"
        upperBound="-1" eType="#//AssemblyContext" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assemblyConnectors" upperBound="-1"
        eType="#//AssemblyConnector" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="delegationConnectors" upperBound="-1"
        eType="#//DelegationConnector" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//Link" eOpposite="#//Link/containers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface" lowerBound="1"
        eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedAssemblyContext"
        eType="#//AssemblyContext" eOpposite="#//AssemblyContext/providedRoles"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredAssemblyContext"
        eType="#//AssemblyContext" eOpposite="#//AssemblyContext/requiredRoles"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containers" lowerBound="2"
        upperBound="-1" eType="#//Container" eOpposite="#//Container/links"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Allocation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocationContexts" upperBound="-1"
        eType="#//AllocationContext" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AllocationContext">
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" lowerBound="1"
        eType="#//Container"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assemblyContext" lowerBound="1"
        eType="#//AssemblyContext" eOpposite="#//AssemblyContext/allocationContext"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Environment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//Link" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containers" upperBound="-1"
        eType="#//Container" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="repository" lowerBound="1"
        upperBound="-1" eType="#//Repository" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="system" upperBound="-1"
        eType="#//System" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssemblyConnector">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="connectedRolesAreInSameContainerOrLinkedContainers"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="connectedRolesAreInSameContainerOrLinkedContainers" value="&#xA;&#x9;&#x9;if self.providedRole.providedAssemblyContext.allocationContext &lt;> null and &#xA;&#x9;&#x9;&#x9;self.requiredRole.requiredAssemblyContext.allocationContext &lt;> null&#xA;&#x9;&#x9;then&#xA;&#x9;&#x9;&#x9;let provCont : Container = self.providedRole.providedAssemblyContext.allocationContext.container in&#xA;&#x9;&#x9;&#x9;let reqCont : Container = self.requiredRole.requiredAssemblyContext.allocationContext.container in&#xA;&#x9;&#x9;&#x9;provCont = reqCont or&#xA;&#x9;&#x9;&#x9;provCont.links->exists(l | l->includes(reqCont))&#xA;&#x9;&#x9;else&#xA;&#x9;&#x9;&#x9;true&#xA;&#x9;&#x9;endif"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedRole" lowerBound="1"
        eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredRole" lowerBound="1"
        eType="#//Role"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DelegationConnector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="role" lowerBound="1" eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface" lowerBound="1"
        eType="#//Interface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SimpleTypeEnum">
    <eLiterals name="Boolean"/>
    <eLiterals name="Char" value="1"/>
    <eLiterals name="Date" value="2"/>
    <eLiterals name="Double" value="3"/>
    <eLiterals name="Float" value="4"/>
    <eLiterals name="List" value="5"/>
    <eLiterals name="Int" value="6"/>
    <eLiterals name="Long" value="7"/>
    <eLiterals name="Map" value="8"/>
    <eLiterals name="String" value="9"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//SimpleTypeEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicComponent" eSuperTypes="#//Component"/>
</ecore:EPackage>
