/*
 * generated by Xtext 2.38.0
 */
package org.xtext.componentsystem.dsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.componentsystem.dsl.ide.contentassist.antlr.internal.InternalDslParser;
import org.xtext.componentsystem.dsl.services.DslGrammarAccess;

public class DslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(DslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, DslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
			builder.put(grammarAccess.getActionAccess().getAlternatives(), "rule__Action__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getSimpleTypeEnumAccess().getAlternatives(), "rule__SimpleTypeEnum__Alternatives");
			builder.put(grammarAccess.getComponentSystemAccess().getGroup(), "rule__ComponentSystem__Group__0");
			builder.put(grammarAccess.getComponentSystemAccess().getGroup_5(), "rule__ComponentSystem__Group_5__0");
			builder.put(grammarAccess.getComponentSystemAccess().getGroup_7(), "rule__ComponentSystem__Group_7__0");
			builder.put(grammarAccess.getComponentSystemAccess().getGroup_7_3(), "rule__ComponentSystem__Group_7_3__0");
			builder.put(grammarAccess.getRepositoryAccess().getGroup(), "rule__Repository__Group__0");
			builder.put(grammarAccess.getRepositoryAccess().getGroup_3(), "rule__Repository__Group_3__0");
			builder.put(grammarAccess.getRepositoryAccess().getGroup_3_3(), "rule__Repository__Group_3_3__0");
			builder.put(grammarAccess.getRepositoryAccess().getGroup_4(), "rule__Repository__Group_4__0");
			builder.put(grammarAccess.getRepositoryAccess().getGroup_4_3(), "rule__Repository__Group_4_3__0");
			builder.put(grammarAccess.getRepositoryAccess().getGroup_5(), "rule__Repository__Group_5__0");
			builder.put(grammarAccess.getRepositoryAccess().getGroup_5_3(), "rule__Repository__Group_5_3__0");
			builder.put(grammarAccess.getSystemAccess().getGroup(), "rule__System__Group__0");
			builder.put(grammarAccess.getSystemAccess().getGroup_5(), "rule__System__Group_5__0");
			builder.put(grammarAccess.getBasicComponentAccess().getGroup(), "rule__BasicComponent__Group__0");
			builder.put(grammarAccess.getBasicComponentAccess().getGroup_4(), "rule__BasicComponent__Group_4__0");
			builder.put(grammarAccess.getBasicComponentAccess().getGroup_4_3(), "rule__BasicComponent__Group_4_3__0");
			builder.put(grammarAccess.getBasicComponentAccess().getGroup_5(), "rule__BasicComponent__Group_5__0");
			builder.put(grammarAccess.getBasicComponentAccess().getGroup_5_3(), "rule__BasicComponent__Group_5_3__0");
			builder.put(grammarAccess.getBasicComponentAccess().getGroup_6(), "rule__BasicComponent__Group_6__0");
			builder.put(grammarAccess.getBasicComponentAccess().getGroup_6_3(), "rule__BasicComponent__Group_6_3__0");
			builder.put(grammarAccess.getBasicComponentAccess().getGroup_7(), "rule__BasicComponent__Group_7__0");
			builder.put(grammarAccess.getBasicComponentAccess().getGroup_7_3(), "rule__BasicComponent__Group_7_3__0");
			builder.put(grammarAccess.getInterfaceAccess().getGroup(), "rule__Interface__Group__0");
			builder.put(grammarAccess.getInterfaceAccess().getGroup_4(), "rule__Interface__Group_4__0");
			builder.put(grammarAccess.getInterfaceAccess().getGroup_4_3(), "rule__Interface__Group_4_3__0");
			builder.put(grammarAccess.getServiceAccess().getGroup(), "rule__Service__Group__0");
			builder.put(grammarAccess.getSignatureAccess().getGroup(), "rule__Signature__Group__0");
			builder.put(grammarAccess.getSignatureAccess().getGroup_4(), "rule__Signature__Group_4__0");
			builder.put(grammarAccess.getSignatureAccess().getGroup_5(), "rule__Signature__Group_5__0");
			builder.put(grammarAccess.getSignatureAccess().getGroup_5_3(), "rule__Signature__Group_5_3__0");
			builder.put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
			builder.put(grammarAccess.getExternalCallAccess().getGroup(), "rule__ExternalCall__Group__0");
			builder.put(grammarAccess.getInternalActionAccess().getGroup(), "rule__InternalAction__Group__0");
			builder.put(grammarAccess.getBranchAccess().getGroup(), "rule__Branch__Group__0");
			builder.put(grammarAccess.getBranchAccess().getGroup_5(), "rule__Branch__Group_5__0");
			builder.put(grammarAccess.getBranchAccess().getGroup_5_3(), "rule__Branch__Group_5_3__0");
			builder.put(grammarAccess.getLoopAccess().getGroup(), "rule__Loop__Group__0");
			builder.put(grammarAccess.getLoopAccess().getGroup_5(), "rule__Loop__Group_5__0");
			builder.put(grammarAccess.getLoopAccess().getGroup_5_3(), "rule__Loop__Group_5_3__0");
			builder.put(grammarAccess.getComplexTypeAccess().getGroup(), "rule__ComplexType__Group__0");
			builder.put(grammarAccess.getSimpleTypeAccess().getGroup(), "rule__SimpleType__Group__0");
			builder.put(grammarAccess.getAssemblyAccess().getGroup(), "rule__Assembly__Group__0");
			builder.put(grammarAccess.getAssemblyAccess().getGroup_3(), "rule__Assembly__Group_3__0");
			builder.put(grammarAccess.getAssemblyAccess().getGroup_3_3(), "rule__Assembly__Group_3_3__0");
			builder.put(grammarAccess.getAssemblyAccess().getGroup_4(), "rule__Assembly__Group_4__0");
			builder.put(grammarAccess.getAssemblyAccess().getGroup_4_3(), "rule__Assembly__Group_4_3__0");
			builder.put(grammarAccess.getAssemblyAccess().getGroup_5(), "rule__Assembly__Group_5__0");
			builder.put(grammarAccess.getAssemblyAccess().getGroup_5_3(), "rule__Assembly__Group_5_3__0");
			builder.put(grammarAccess.getAssemblyAccess().getGroup_6(), "rule__Assembly__Group_6__0");
			builder.put(grammarAccess.getAssemblyAccess().getGroup_6_3(), "rule__Assembly__Group_6_3__0");
			builder.put(grammarAccess.getAllocationAccess().getGroup(), "rule__Allocation__Group__0");
			builder.put(grammarAccess.getAllocationAccess().getGroup_3(), "rule__Allocation__Group_3__0");
			builder.put(grammarAccess.getAllocationAccess().getGroup_3_3(), "rule__Allocation__Group_3_3__0");
			builder.put(grammarAccess.getEnvironmentAccess().getGroup(), "rule__Environment__Group__0");
			builder.put(grammarAccess.getEnvironmentAccess().getGroup_3(), "rule__Environment__Group_3__0");
			builder.put(grammarAccess.getEnvironmentAccess().getGroup_3_3(), "rule__Environment__Group_3_3__0");
			builder.put(grammarAccess.getEnvironmentAccess().getGroup_4(), "rule__Environment__Group_4__0");
			builder.put(grammarAccess.getEnvironmentAccess().getGroup_4_3(), "rule__Environment__Group_4_3__0");
			builder.put(grammarAccess.getAssemblyContextAccess().getGroup(), "rule__AssemblyContext__Group__0");
			builder.put(grammarAccess.getAssemblyContextAccess().getGroup_5(), "rule__AssemblyContext__Group_5__0");
			builder.put(grammarAccess.getAssemblyContextAccess().getGroup_6(), "rule__AssemblyContext__Group_6__0");
			builder.put(grammarAccess.getAssemblyContextAccess().getGroup_6_3(), "rule__AssemblyContext__Group_6_3__0");
			builder.put(grammarAccess.getAssemblyContextAccess().getGroup_7(), "rule__AssemblyContext__Group_7__0");
			builder.put(grammarAccess.getAssemblyContextAccess().getGroup_7_3(), "rule__AssemblyContext__Group_7_3__0");
			builder.put(grammarAccess.getCompositeComponentAccess().getGroup(), "rule__CompositeComponent__Group__0");
			builder.put(grammarAccess.getCompositeComponentAccess().getGroup_3(), "rule__CompositeComponent__Group_3__0");
			builder.put(grammarAccess.getCompositeComponentAccess().getGroup_3_3(), "rule__CompositeComponent__Group_3_3__0");
			builder.put(grammarAccess.getCompositeComponentAccess().getGroup_4(), "rule__CompositeComponent__Group_4__0");
			builder.put(grammarAccess.getCompositeComponentAccess().getGroup_4_3(), "rule__CompositeComponent__Group_4_3__0");
			builder.put(grammarAccess.getCompositeComponentAccess().getGroup_5(), "rule__CompositeComponent__Group_5__0");
			builder.put(grammarAccess.getCompositeComponentAccess().getGroup_5_3(), "rule__CompositeComponent__Group_5_3__0");
			builder.put(grammarAccess.getCompositeComponentAccess().getGroup_6(), "rule__CompositeComponent__Group_6__0");
			builder.put(grammarAccess.getCompositeComponentAccess().getGroup_6_3(), "rule__CompositeComponent__Group_6_3__0");
			builder.put(grammarAccess.getCompositeComponentAccess().getGroup_10(), "rule__CompositeComponent__Group_10__0");
			builder.put(grammarAccess.getCompositeComponentAccess().getGroup_12(), "rule__CompositeComponent__Group_12__0");
			builder.put(grammarAccess.getCompositeComponentAccess().getGroup_12_3(), "rule__CompositeComponent__Group_12_3__0");
			builder.put(grammarAccess.getCompositeComponentAccess().getGroup_13(), "rule__CompositeComponent__Group_13__0");
			builder.put(grammarAccess.getCompositeComponentAccess().getGroup_13_3(), "rule__CompositeComponent__Group_13_3__0");
			builder.put(grammarAccess.getAssemblyConnectorAccess().getGroup(), "rule__AssemblyConnector__Group__0");
			builder.put(grammarAccess.getDelegationConnectorAccess().getGroup(), "rule__DelegationConnector__Group__0");
			builder.put(grammarAccess.getRoleAccess().getGroup(), "rule__Role__Group__0");
			builder.put(grammarAccess.getAllocationContextAccess().getGroup(), "rule__AllocationContext__Group__0");
			builder.put(grammarAccess.getContainerAccess().getGroup(), "rule__Container__Group__0");
			builder.put(grammarAccess.getContainerAccess().getGroup_4(), "rule__Container__Group_4__0");
			builder.put(grammarAccess.getContainerAccess().getGroup_4_3(), "rule__Container__Group_4_3__0");
			builder.put(grammarAccess.getLinkAccess().getGroup(), "rule__Link__Group__0");
			builder.put(grammarAccess.getLinkAccess().getGroup_6(), "rule__Link__Group_6__0");
			builder.put(grammarAccess.getComponentSystemAccess().getRepositoriesAssignment_4(), "rule__ComponentSystem__RepositoriesAssignment_4");
			builder.put(grammarAccess.getComponentSystemAccess().getRepositoriesAssignment_5_1(), "rule__ComponentSystem__RepositoriesAssignment_5_1");
			builder.put(grammarAccess.getComponentSystemAccess().getSystemsAssignment_7_2(), "rule__ComponentSystem__SystemsAssignment_7_2");
			builder.put(grammarAccess.getComponentSystemAccess().getSystemsAssignment_7_3_1(), "rule__ComponentSystem__SystemsAssignment_7_3_1");
			builder.put(grammarAccess.getRepositoryAccess().getComponentsAssignment_3_2(), "rule__Repository__ComponentsAssignment_3_2");
			builder.put(grammarAccess.getRepositoryAccess().getComponentsAssignment_3_3_1(), "rule__Repository__ComponentsAssignment_3_3_1");
			builder.put(grammarAccess.getRepositoryAccess().getInterfacesAssignment_4_2(), "rule__Repository__InterfacesAssignment_4_2");
			builder.put(grammarAccess.getRepositoryAccess().getInterfacesAssignment_4_3_1(), "rule__Repository__InterfacesAssignment_4_3_1");
			builder.put(grammarAccess.getRepositoryAccess().getTypesAssignment_5_2(), "rule__Repository__TypesAssignment_5_2");
			builder.put(grammarAccess.getRepositoryAccess().getTypesAssignment_5_3_1(), "rule__Repository__TypesAssignment_5_3_1");
			builder.put(grammarAccess.getSystemAccess().getInterfacesAssignment_4(), "rule__System__InterfacesAssignment_4");
			builder.put(grammarAccess.getSystemAccess().getInterfacesAssignment_5_1(), "rule__System__InterfacesAssignment_5_1");
			builder.put(grammarAccess.getSystemAccess().getAssemblyAssignment_8(), "rule__System__AssemblyAssignment_8");
			builder.put(grammarAccess.getSystemAccess().getAllocationAssignment_10(), "rule__System__AllocationAssignment_10");
			builder.put(grammarAccess.getSystemAccess().getEnvironmentAssignment_12(), "rule__System__EnvironmentAssignment_12");
			builder.put(grammarAccess.getBasicComponentAccess().getNameAssignment_2(), "rule__BasicComponent__NameAssignment_2");
			builder.put(grammarAccess.getBasicComponentAccess().getProvidedInterfacesAssignment_4_2(), "rule__BasicComponent__ProvidedInterfacesAssignment_4_2");
			builder.put(grammarAccess.getBasicComponentAccess().getProvidedInterfacesAssignment_4_3_1(), "rule__BasicComponent__ProvidedInterfacesAssignment_4_3_1");
			builder.put(grammarAccess.getBasicComponentAccess().getRequiredInterfacesAssignment_5_2(), "rule__BasicComponent__RequiredInterfacesAssignment_5_2");
			builder.put(grammarAccess.getBasicComponentAccess().getRequiredInterfacesAssignment_5_3_1(), "rule__BasicComponent__RequiredInterfacesAssignment_5_3_1");
			builder.put(grammarAccess.getBasicComponentAccess().getProvidedServicesAssignment_6_2(), "rule__BasicComponent__ProvidedServicesAssignment_6_2");
			builder.put(grammarAccess.getBasicComponentAccess().getProvidedServicesAssignment_6_3_1(), "rule__BasicComponent__ProvidedServicesAssignment_6_3_1");
			builder.put(grammarAccess.getBasicComponentAccess().getBehaviorDescriptionAssignment_7_2(), "rule__BasicComponent__BehaviorDescriptionAssignment_7_2");
			builder.put(grammarAccess.getBasicComponentAccess().getBehaviorDescriptionAssignment_7_3_1(), "rule__BasicComponent__BehaviorDescriptionAssignment_7_3_1");
			builder.put(grammarAccess.getInterfaceAccess().getNameAssignment_2(), "rule__Interface__NameAssignment_2");
			builder.put(grammarAccess.getInterfaceAccess().getSignaturesAssignment_4_2(), "rule__Interface__SignaturesAssignment_4_2");
			builder.put(grammarAccess.getInterfaceAccess().getSignaturesAssignment_4_3_1(), "rule__Interface__SignaturesAssignment_4_3_1");
			builder.put(grammarAccess.getServiceAccess().getNameAssignment_1(), "rule__Service__NameAssignment_1");
			builder.put(grammarAccess.getServiceAccess().getCorrespondingSignatureAssignment_4(), "rule__Service__CorrespondingSignatureAssignment_4");
			builder.put(grammarAccess.getSignatureAccess().getNameAssignment_2(), "rule__Signature__NameAssignment_2");
			builder.put(grammarAccess.getSignatureAccess().getReturnTypeAssignment_4_1(), "rule__Signature__ReturnTypeAssignment_4_1");
			builder.put(grammarAccess.getSignatureAccess().getParametersAssignment_5_2(), "rule__Signature__ParametersAssignment_5_2");
			builder.put(grammarAccess.getSignatureAccess().getParametersAssignment_5_3_1(), "rule__Signature__ParametersAssignment_5_3_1");
			builder.put(grammarAccess.getParameterAccess().getNameAssignment_1(), "rule__Parameter__NameAssignment_1");
			builder.put(grammarAccess.getParameterAccess().getTypeAssignment_4(), "rule__Parameter__TypeAssignment_4");
			builder.put(grammarAccess.getExternalCallAccess().getNameAssignment_2(), "rule__ExternalCall__NameAssignment_2");
			builder.put(grammarAccess.getInternalActionAccess().getNameAssignment_2(), "rule__InternalAction__NameAssignment_2");
			builder.put(grammarAccess.getBranchAccess().getNameAssignment_1(), "rule__Branch__NameAssignment_1");
			builder.put(grammarAccess.getBranchAccess().getConditionAssignment_4(), "rule__Branch__ConditionAssignment_4");
			builder.put(grammarAccess.getBranchAccess().getActionsAssignment_5_2(), "rule__Branch__ActionsAssignment_5_2");
			builder.put(grammarAccess.getBranchAccess().getActionsAssignment_5_3_1(), "rule__Branch__ActionsAssignment_5_3_1");
			builder.put(grammarAccess.getLoopAccess().getNameAssignment_1(), "rule__Loop__NameAssignment_1");
			builder.put(grammarAccess.getLoopAccess().getConditionAssignment_4(), "rule__Loop__ConditionAssignment_4");
			builder.put(grammarAccess.getLoopAccess().getActionsAssignment_5_2(), "rule__Loop__ActionsAssignment_5_2");
			builder.put(grammarAccess.getLoopAccess().getActionsAssignment_5_3_1(), "rule__Loop__ActionsAssignment_5_3_1");
			builder.put(grammarAccess.getComplexTypeAccess().getNameAssignment_1(), "rule__ComplexType__NameAssignment_1");
			builder.put(grammarAccess.getComplexTypeAccess().getTypeAssignment_4(), "rule__ComplexType__TypeAssignment_4");
			builder.put(grammarAccess.getSimpleTypeAccess().getNameAssignment_1(), "rule__SimpleType__NameAssignment_1");
			builder.put(grammarAccess.getSimpleTypeAccess().getTypeAssignment_4(), "rule__SimpleType__TypeAssignment_4");
			builder.put(grammarAccess.getAssemblyAccess().getAssemblyContextsAssignment_3_2(), "rule__Assembly__AssemblyContextsAssignment_3_2");
			builder.put(grammarAccess.getAssemblyAccess().getAssemblyContextsAssignment_3_3_1(), "rule__Assembly__AssemblyContextsAssignment_3_3_1");
			builder.put(grammarAccess.getAssemblyAccess().getCompositeComponentsAssignment_4_2(), "rule__Assembly__CompositeComponentsAssignment_4_2");
			builder.put(grammarAccess.getAssemblyAccess().getCompositeComponentsAssignment_4_3_1(), "rule__Assembly__CompositeComponentsAssignment_4_3_1");
			builder.put(grammarAccess.getAssemblyAccess().getAssemblyConnectorsAssignment_5_2(), "rule__Assembly__AssemblyConnectorsAssignment_5_2");
			builder.put(grammarAccess.getAssemblyAccess().getAssemblyConnectorsAssignment_5_3_1(), "rule__Assembly__AssemblyConnectorsAssignment_5_3_1");
			builder.put(grammarAccess.getAssemblyAccess().getDelegationConnectorsAssignment_6_2(), "rule__Assembly__DelegationConnectorsAssignment_6_2");
			builder.put(grammarAccess.getAssemblyAccess().getDelegationConnectorsAssignment_6_3_1(), "rule__Assembly__DelegationConnectorsAssignment_6_3_1");
			builder.put(grammarAccess.getAllocationAccess().getAllocationContextsAssignment_3_2(), "rule__Allocation__AllocationContextsAssignment_3_2");
			builder.put(grammarAccess.getAllocationAccess().getAllocationContextsAssignment_3_3_1(), "rule__Allocation__AllocationContextsAssignment_3_3_1");
			builder.put(grammarAccess.getEnvironmentAccess().getLinksAssignment_3_2(), "rule__Environment__LinksAssignment_3_2");
			builder.put(grammarAccess.getEnvironmentAccess().getLinksAssignment_3_3_1(), "rule__Environment__LinksAssignment_3_3_1");
			builder.put(grammarAccess.getEnvironmentAccess().getContainersAssignment_4_2(), "rule__Environment__ContainersAssignment_4_2");
			builder.put(grammarAccess.getEnvironmentAccess().getContainersAssignment_4_3_1(), "rule__Environment__ContainersAssignment_4_3_1");
			builder.put(grammarAccess.getAssemblyContextAccess().getNameAssignment_1(), "rule__AssemblyContext__NameAssignment_1");
			builder.put(grammarAccess.getAssemblyContextAccess().getComponentAssignment_4(), "rule__AssemblyContext__ComponentAssignment_4");
			builder.put(grammarAccess.getAssemblyContextAccess().getAllocationContextAssignment_5_1(), "rule__AssemblyContext__AllocationContextAssignment_5_1");
			builder.put(grammarAccess.getAssemblyContextAccess().getProvidedRolesAssignment_6_2(), "rule__AssemblyContext__ProvidedRolesAssignment_6_2");
			builder.put(grammarAccess.getAssemblyContextAccess().getProvidedRolesAssignment_6_3_1(), "rule__AssemblyContext__ProvidedRolesAssignment_6_3_1");
			builder.put(grammarAccess.getAssemblyContextAccess().getRequiredRolesAssignment_7_2(), "rule__AssemblyContext__RequiredRolesAssignment_7_2");
			builder.put(grammarAccess.getAssemblyContextAccess().getRequiredRolesAssignment_7_3_1(), "rule__AssemblyContext__RequiredRolesAssignment_7_3_1");
			builder.put(grammarAccess.getCompositeComponentAccess().getNameAssignment_1(), "rule__CompositeComponent__NameAssignment_1");
			builder.put(grammarAccess.getCompositeComponentAccess().getProvidedInterfacesAssignment_3_2(), "rule__CompositeComponent__ProvidedInterfacesAssignment_3_2");
			builder.put(grammarAccess.getCompositeComponentAccess().getProvidedInterfacesAssignment_3_3_1(), "rule__CompositeComponent__ProvidedInterfacesAssignment_3_3_1");
			builder.put(grammarAccess.getCompositeComponentAccess().getRequiredInterfacesAssignment_4_2(), "rule__CompositeComponent__RequiredInterfacesAssignment_4_2");
			builder.put(grammarAccess.getCompositeComponentAccess().getRequiredInterfacesAssignment_4_3_1(), "rule__CompositeComponent__RequiredInterfacesAssignment_4_3_1");
			builder.put(grammarAccess.getCompositeComponentAccess().getProvidedServicesAssignment_5_2(), "rule__CompositeComponent__ProvidedServicesAssignment_5_2");
			builder.put(grammarAccess.getCompositeComponentAccess().getProvidedServicesAssignment_5_3_1(), "rule__CompositeComponent__ProvidedServicesAssignment_5_3_1");
			builder.put(grammarAccess.getCompositeComponentAccess().getBehaviorDescriptionAssignment_6_2(), "rule__CompositeComponent__BehaviorDescriptionAssignment_6_2");
			builder.put(grammarAccess.getCompositeComponentAccess().getBehaviorDescriptionAssignment_6_3_1(), "rule__CompositeComponent__BehaviorDescriptionAssignment_6_3_1");
			builder.put(grammarAccess.getCompositeComponentAccess().getAssemblyContextsAssignment_9(), "rule__CompositeComponent__AssemblyContextsAssignment_9");
			builder.put(grammarAccess.getCompositeComponentAccess().getAssemblyContextsAssignment_10_1(), "rule__CompositeComponent__AssemblyContextsAssignment_10_1");
			builder.put(grammarAccess.getCompositeComponentAccess().getAssemblyConnectorsAssignment_12_2(), "rule__CompositeComponent__AssemblyConnectorsAssignment_12_2");
			builder.put(grammarAccess.getCompositeComponentAccess().getAssemblyConnectorsAssignment_12_3_1(), "rule__CompositeComponent__AssemblyConnectorsAssignment_12_3_1");
			builder.put(grammarAccess.getCompositeComponentAccess().getDelegationConnectorsAssignment_13_2(), "rule__CompositeComponent__DelegationConnectorsAssignment_13_2");
			builder.put(grammarAccess.getCompositeComponentAccess().getDelegationConnectorsAssignment_13_3_1(), "rule__CompositeComponent__DelegationConnectorsAssignment_13_3_1");
			builder.put(grammarAccess.getAssemblyConnectorAccess().getNameAssignment_1(), "rule__AssemblyConnector__NameAssignment_1");
			builder.put(grammarAccess.getAssemblyConnectorAccess().getProvidedRoleAssignment_4(), "rule__AssemblyConnector__ProvidedRoleAssignment_4");
			builder.put(grammarAccess.getAssemblyConnectorAccess().getRequiredRoleAssignment_6(), "rule__AssemblyConnector__RequiredRoleAssignment_6");
			builder.put(grammarAccess.getDelegationConnectorAccess().getNameAssignment_1(), "rule__DelegationConnector__NameAssignment_1");
			builder.put(grammarAccess.getDelegationConnectorAccess().getRoleAssignment_4(), "rule__DelegationConnector__RoleAssignment_4");
			builder.put(grammarAccess.getDelegationConnectorAccess().getDelegatedInterfaceAssignment_6(), "rule__DelegationConnector__DelegatedInterfaceAssignment_6");
			builder.put(grammarAccess.getRoleAccess().getNameAssignment_1(), "rule__Role__NameAssignment_1");
			builder.put(grammarAccess.getRoleAccess().getInterfaceAssignment_4(), "rule__Role__InterfaceAssignment_4");
			builder.put(grammarAccess.getAllocationContextAccess().getNameAssignment_1(), "rule__AllocationContext__NameAssignment_1");
			builder.put(grammarAccess.getAllocationContextAccess().getContainerAssignment_4(), "rule__AllocationContext__ContainerAssignment_4");
			builder.put(grammarAccess.getAllocationContextAccess().getAssemblyContextAssignment_6(), "rule__AllocationContext__AssemblyContextAssignment_6");
			builder.put(grammarAccess.getContainerAccess().getNameAssignment_2(), "rule__Container__NameAssignment_2");
			builder.put(grammarAccess.getContainerAccess().getLinksAssignment_4_2(), "rule__Container__LinksAssignment_4_2");
			builder.put(grammarAccess.getContainerAccess().getLinksAssignment_4_3_1(), "rule__Container__LinksAssignment_4_3_1");
			builder.put(grammarAccess.getLinkAccess().getNameAssignment_1(), "rule__Link__NameAssignment_1");
			builder.put(grammarAccess.getLinkAccess().getContainersAssignment_5(), "rule__Link__ContainersAssignment_5");
			builder.put(grammarAccess.getLinkAccess().getContainersAssignment_6_1(), "rule__Link__ContainersAssignment_6_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private DslGrammarAccess grammarAccess;

	@Override
	protected InternalDslParser createParser() {
		InternalDslParser result = new InternalDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
